name: todo_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^6.5.2
  flutter_adaptive_scaffold: ^0.1.2
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_bloc: ^8.1.2
  http: ^0.13.5
  snippet_coder_utils: ^1.0.13
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
